#!/usr/bin/env python

import sys
import time
import pexpect

def main(argv):
    if len(argv) == 1:
        print 'Usage:', argv[0], '[-n VALUE] [-s VALUE] FILE [FILE ...]'
        sys.exit(-1)

    r = 1
    start = 1
    interval = 10
    if argv[1] == '-n':
        r = 3
        interval = int(argv[2])
    if argv[3] == '-s':
        r = 5
        start = int(argv[4])

    child = pexpect.spawn('gnuplot')
    child.sendline('set terminal x11 noraise')
    child.sendline('unset key')
    child.sendline('set xlabel "Monte Carlo cycles"')
    child.sendline('set ylabel "Potential energy"')
    child.sendline('set grid')
    s = 'plot '
    for x in argv[r:-1]:
        s += "'%s' every %u::%u with lines, " % (x, interval, start)
    s += "'%s' every %u::%u with lines" % (argv[-1], interval, start)
    child.sendline(s)
    child.sendline('replot')
    while True:
        time.sleep(60)
        child.sendline('replot')

if __name__ == '__main__':
    main(sys.argv)
